AWSTemplateFormatVersion: '2010-09-09'
Description: 'Minimal AWS App Runner deployment for Next.js Finances Dashboard'

Parameters:
  ContainerImageUri:
    Type: String
    Description: Container image URI from ECR
  
  DBUrl:
    Type: String
    Description: Database connection URL
    NoEcho: true
  
  DBName:
    Type: String
    Description: Database name
    NoEcho: true
  
  Environment:
    Type: String
    Description: Environment name (dev, staging, prod)
    Default: prod
    AllowedValues: [dev, staging, prod]
  
  MaxInstances:
    Type: Number
    Description: Maximum number of instances for auto-scaling
    Default: 1
    MinValue: 1
    MaxValue: 25

Resources:
  # IAM Role for App Runner to access ECR (REQUIRED)
  AppRunnerAccessRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: build.apprunner.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppRunnerServicePolicyForECRAccess

  # App Runner Service (CORE SERVICE)
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub ${AWS::StackName}-nextjs
      SourceConfiguration:
        ImageRepository:
          ImageIdentifier: !Ref ContainerImageUri
          ImageConfiguration:
            Port: '3000'
            RuntimeEnvironmentVariables:
              NODE_ENV: !Ref Environment
              DB_URL: !Ref DBUrl
              DB_NAME: !Ref DBName
              NEXT_TELEMETRY_DISABLED: '1'
          ImageRepositoryType: ECR
        AutoDeploymentsEnabled: false
        AccessRoleArn: !GetAtt AppRunnerAccessRole.Arn
      InstanceConfiguration:
        Cpu: '0.25 vCPU'
        Memory: '0.5 GB'
      HealthCheckConfiguration:
        Protocol: HTTP
        Path: '/api/health'
        Interval: 20
        Timeout: 10
        HealthyThreshold: 1
        UnhealthyThreshold: 5
      AutoScalingConfigurationArn: !Ref AppRunnerAutoScalingConfig

  # Auto Scaling Configuration
  AppRunnerAutoScalingConfig:
    Type: AWS::AppRunner::AutoScalingConfiguration
    Properties:
      AutoScalingConfigurationName: !Sub ${AWS::StackName}-autoscaling
      MinSize: 0
      MaxSize: !Ref MaxInstances
      MaxConcurrency: 100

Outputs:
  AppRunnerServiceUrl:
    Description: App Runner Service URL
    Value: !Sub https://${AppRunnerService.ServiceUrl}
    Export:
      Name: !Sub ${AWS::StackName}-AppRunnerUrl
  
  AppRunnerServiceId:
    Description: App Runner Service ID
    Value: !Ref AppRunnerService
    Export:
      Name: !Sub ${AWS::StackName}-AppRunnerServiceId
